ASAP (Annoyingly Simple ANTLR Parsers). Domain-specific parsers that turn natural language into structured data. Each parser takes a paragraph of plain text and returns a typed result or nil.

** Workout Parser

Parses natural workout descriptions into structured exercise data.

*** Example

Input:
#+begin_example
ate a banana beforehand
squat 8 8 8 225
bench 3x8 155
#+end_example

Output: =WorkoutResult= with exercises =[Exercise(name: "Squat", sets: [8@225, 8@225, 8@225]), Exercise(name: "Bench", sets: [8@155, 8@155, 8@155])]= and prose =["ate a banana beforehand"]=.

*** Syntax

| Notation         | Meaning                        |
|------------------+--------------------------------|
| =squat 225=      | 1 set of 8 reps @ 225          |
| =squat 8 8 225=  | 2 sets of 8 reps @ 225         |
| =squat 3x8 225=  | 3 sets of 8 reps @ 225         |
| =squat 3x8x225=  | 3 sets of 8 reps @ 225         |
| =squat 8 by 225= | 3 sets of 8 reps @ 225         |
| =squat 3 by 8 by 225= | 3 sets of 8 reps @ 225    |

Prose lines (no numbers) are preserved in =proseLines=. Inline notes (words after numbers) attach to the preceding set.

** Go CLI

#+begin_src bash
# Build
make build

# Usage
echo "squat 3x8 225" | ./asap
./asap < workout.txt
./asap workout.txt
#+end_src

** Swift Library

Add to Xcode project (/cough cough/ [[https://github.com/chinarjoshi/omfg][omfg]] /cough/):

#+begin_src swift
dependencies: [
    .package(path: "path/to/asap/swift")
]
#+end_src

Usage:

#+begin_src swift
import WorkoutParser

let result = parse("squat 3x8 225")
// result: WorkoutResult? with exercises and proseLines
#+end_src

** Structure

#+begin_example
Workoutliner.g4          # ANTLR grammar (workout)
libs/workout/            # Go parser library
cmd/asap/                # Go CLI
swift/                   # Swift library
#+end_example
