/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_COLON = 2,
  anon_sym_DASH = 3,
  sym_word = 4,
  sym_number = 5,
  sym_punctuation = 6,
  sym_recipe = 7,
  sym__line_content = 8,
  sym_header_line = 9,
  sym_ingredient_line = 10,
  sym_text_line = 11,
  sym_quantity = 12,
  aux_sym_recipe_repeat1 = 13,
  aux_sym_header_line_repeat1 = 14,
  aux_sym_ingredient_line_repeat1 = 15,
  aux_sym_text_line_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH] = "-",
  [sym_word] = "word",
  [sym_number] = "number",
  [sym_punctuation] = "punctuation",
  [sym_recipe] = "recipe",
  [sym__line_content] = "_line_content",
  [sym_header_line] = "header_line",
  [sym_ingredient_line] = "ingredient_line",
  [sym_text_line] = "text_line",
  [sym_quantity] = "quantity",
  [aux_sym_recipe_repeat1] = "recipe_repeat1",
  [aux_sym_header_line_repeat1] = "header_line_repeat1",
  [aux_sym_ingredient_line_repeat1] = "ingredient_line_repeat1",
  [aux_sym_text_line_repeat1] = "text_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_word] = sym_word,
  [sym_number] = sym_number,
  [sym_punctuation] = sym_punctuation,
  [sym_recipe] = sym_recipe,
  [sym__line_content] = sym__line_content,
  [sym_header_line] = sym_header_line,
  [sym_ingredient_line] = sym_ingredient_line,
  [sym_text_line] = sym_text_line,
  [sym_quantity] = sym_quantity,
  [aux_sym_recipe_repeat1] = aux_sym_recipe_repeat1,
  [aux_sym_header_line_repeat1] = aux_sym_header_line_repeat1,
  [aux_sym_ingredient_line_repeat1] = aux_sym_ingredient_line_repeat1,
  [aux_sym_text_line_repeat1] = aux_sym_text_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe] = {
    .visible = true,
    .named = true,
  },
  [sym__line_content] = {
    .visible = false,
    .named = true,
  },
  [sym_header_line] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredient_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_recipe_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ingredient_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_max = 1,
  field_min = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_max] = "max",
  [field_min] = "min",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 0},
  [1] =
    {field_max, 2},
    {field_min, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(8);
      END_STATE();
    case 1:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(8);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          (lookahead < '0' || ':' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(8);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_word);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          (lookahead < '0' || ':' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(8);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_recipe] = STATE(18),
    [sym__line_content] = STATE(9),
    [sym_header_line] = STATE(9),
    [sym_ingredient_line] = STATE(9),
    [sym_text_line] = STATE(9),
    [sym_quantity] = STATE(10),
    [aux_sym_header_line_repeat1] = STATE(11),
    [aux_sym_text_line_repeat1] = STATE(5),
    [sym_word] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [sym_punctuation] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__line_content] = STATE(17),
    [sym_header_line] = STATE(17),
    [sym_ingredient_line] = STATE(17),
    [sym_text_line] = STATE(17),
    [sym_quantity] = STATE(10),
    [aux_sym_header_line_repeat1] = STATE(11),
    [aux_sym_text_line_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(9),
    [sym_word] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [sym_punctuation] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      sym_word,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_number,
      sym_punctuation,
  [13] = 4,
    ACTIONS(18), 1,
      anon_sym_DASH,
    ACTIONS(23), 1,
      sym_punctuation,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(20), 2,
      sym_word,
      sym_number,
  [28] = 3,
    STATE(6), 1,
      aux_sym_text_line_repeat1,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(27), 3,
      sym_word,
      sym_number,
      sym_punctuation,
  [41] = 3,
    STATE(6), 1,
      aux_sym_text_line_repeat1,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(31), 3,
      sym_word,
      sym_number,
      sym_punctuation,
  [54] = 3,
    STATE(8), 1,
      aux_sym_ingredient_line_repeat1,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(36), 2,
      sym_word,
      sym_number,
  [66] = 3,
    STATE(8), 1,
      aux_sym_ingredient_line_repeat1,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(40), 2,
      sym_word,
      sym_number,
  [78] = 3,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      anon_sym_LF,
    STATE(12), 1,
      aux_sym_recipe_repeat1,
  [88] = 2,
    STATE(7), 1,
      aux_sym_ingredient_line_repeat1,
    ACTIONS(47), 2,
      sym_word,
      sym_number,
  [96] = 3,
    ACTIONS(49), 1,
      anon_sym_COLON,
    ACTIONS(51), 1,
      sym_word,
    STATE(13), 1,
      aux_sym_header_line_repeat1,
  [106] = 3,
    ACTIONS(45), 1,
      anon_sym_LF,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      aux_sym_recipe_repeat1,
  [116] = 3,
    ACTIONS(55), 1,
      anon_sym_COLON,
    ACTIONS(57), 1,
      sym_word,
    STATE(13), 1,
      aux_sym_header_line_repeat1,
  [126] = 3,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      anon_sym_LF,
    STATE(14), 1,
      aux_sym_recipe_repeat1,
  [136] = 1,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [141] = 1,
    ACTIONS(67), 2,
      sym_word,
      sym_number,
  [146] = 1,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [151] = 1,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
  [155] = 1,
    ACTIONS(71), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 13,
  [SMALL_STATE(5)] = 28,
  [SMALL_STATE(6)] = 41,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 66,
  [SMALL_STATE(9)] = 78,
  [SMALL_STATE(10)] = 88,
  [SMALL_STATE(11)] = 96,
  [SMALL_STATE(12)] = 106,
  [SMALL_STATE(13)] = 116,
  [SMALL_STATE(14)] = 126,
  [SMALL_STATE(15)] = 136,
  [SMALL_STATE(16)] = 141,
  [SMALL_STATE(17)] = 146,
  [SMALL_STATE(18)] = 151,
  [SMALL_STATE(19)] = 155,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_repeat1, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_line_repeat1, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_line_repeat1, 1, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_line_repeat1, 1, 0, 0), REDUCE(aux_sym_text_line_repeat1, 1, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quantity, 1, 0, 1), REDUCE(aux_sym_text_line_repeat1, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_line_repeat1, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_line_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_line_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient_line, 2, 5, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ingredient_line_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ingredient_line_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_line_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_line_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 2, 10, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantity, 3, 0, 2),
  [69] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_recipe(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
