/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_DOT = 2,
  sym_number_literal = 3,
  sym_x_separator = 4,
  sym_by_keyword = 5,
  sym_star = 6,
  sym_word = 7,
  sym_paragraph = 8,
  sym__separator = 9,
  sym__line_content = 10,
  sym_continuation_line = 11,
  sym_superset_line = 12,
  sym_superset_name = 13,
  sym_exercise_line = 14,
  sym_prose_line = 15,
  sym_numeric_token = 16,
  sym_token = 17,
  sym_by_expr = 18,
  sym_two_part_by = 19,
  sym_three_part_by = 20,
  sym_multiplier = 21,
  sym_partial_multiplier = 22,
  sym_full_multiplier = 23,
  sym_number = 24,
  sym_note = 25,
  aux_sym_paragraph_repeat1 = 26,
  aux_sym_continuation_line_repeat1 = 27,
  aux_sym_superset_name_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_DOT] = ".",
  [sym_number_literal] = "number_literal",
  [sym_x_separator] = "x_separator",
  [sym_by_keyword] = "by_keyword",
  [sym_star] = "star",
  [sym_word] = "word",
  [sym_paragraph] = "paragraph",
  [sym__separator] = "_separator",
  [sym__line_content] = "_line_content",
  [sym_continuation_line] = "continuation_line",
  [sym_superset_line] = "superset_line",
  [sym_superset_name] = "superset_name",
  [sym_exercise_line] = "exercise_line",
  [sym_prose_line] = "prose_line",
  [sym_numeric_token] = "numeric_token",
  [sym_token] = "token",
  [sym_by_expr] = "by_expr",
  [sym_two_part_by] = "two_part_by",
  [sym_three_part_by] = "three_part_by",
  [sym_multiplier] = "multiplier",
  [sym_partial_multiplier] = "partial_multiplier",
  [sym_full_multiplier] = "full_multiplier",
  [sym_number] = "number",
  [sym_note] = "note",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_continuation_line_repeat1] = "continuation_line_repeat1",
  [aux_sym_superset_name_repeat1] = "superset_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_number_literal] = sym_number_literal,
  [sym_x_separator] = sym_x_separator,
  [sym_by_keyword] = sym_by_keyword,
  [sym_star] = sym_star,
  [sym_word] = sym_word,
  [sym_paragraph] = sym_paragraph,
  [sym__separator] = sym__separator,
  [sym__line_content] = sym__line_content,
  [sym_continuation_line] = sym_continuation_line,
  [sym_superset_line] = sym_superset_line,
  [sym_superset_name] = sym_superset_name,
  [sym_exercise_line] = sym_exercise_line,
  [sym_prose_line] = sym_prose_line,
  [sym_numeric_token] = sym_numeric_token,
  [sym_token] = sym_token,
  [sym_by_expr] = sym_by_expr,
  [sym_two_part_by] = sym_two_part_by,
  [sym_three_part_by] = sym_three_part_by,
  [sym_multiplier] = sym_multiplier,
  [sym_partial_multiplier] = sym_partial_multiplier,
  [sym_full_multiplier] = sym_full_multiplier,
  [sym_number] = sym_number,
  [sym_note] = sym_note,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_continuation_line_repeat1] = aux_sym_continuation_line_repeat1,
  [aux_sym_superset_name_repeat1] = aux_sym_superset_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_x_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_by_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_star] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__separator] = {
    .visible = false,
    .named = true,
  },
  [sym__line_content] = {
    .visible = false,
    .named = true,
  },
  [sym_continuation_line] = {
    .visible = true,
    .named = true,
  },
  [sym_superset_line] = {
    .visible = true,
    .named = true,
  },
  [sym_superset_name] = {
    .visible = true,
    .named = true,
  },
  [sym_exercise_line] = {
    .visible = true,
    .named = true,
  },
  [sym_prose_line] = {
    .visible = true,
    .named = true,
  },
  [sym_numeric_token] = {
    .visible = true,
    .named = true,
  },
  [sym_token] = {
    .visible = true,
    .named = true,
  },
  [sym_by_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_two_part_by] = {
    .visible = true,
    .named = true,
  },
  [sym_three_part_by] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplier] = {
    .visible = true,
    .named = true,
  },
  [sym_partial_multiplier] = {
    .visible = true,
    .named = true,
  },
  [sym_full_multiplier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_continuation_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_superset_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_reps = 1,
  field_sets = 2,
  field_weight = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_reps] = "reps",
  [field_sets] = "sets",
  [field_weight] = "weight",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_reps, 2},
    {field_sets, 0},
  [2] =
    {field_reps, 0},
    {field_weight, 2},
  [4] =
    {field_reps, 2},
    {field_sets, 0},
    {field_weight, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(11);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 2:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_x_separator);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_by_keyword);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_star);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_word);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_x_separator] = ACTIONS(1),
    [sym_by_keyword] = ACTIONS(1),
    [sym_star] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_paragraph] = STATE(31),
    [sym__line_content] = STATE(17),
    [sym_continuation_line] = STATE(17),
    [sym_superset_line] = STATE(17),
    [sym_superset_name] = STATE(26),
    [sym_exercise_line] = STATE(17),
    [sym_prose_line] = STATE(17),
    [sym_numeric_token] = STATE(4),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [aux_sym_superset_name_repeat1] = STATE(9),
    [sym_number_literal] = ACTIONS(3),
    [sym_word] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__line_content] = STATE(27),
    [sym_continuation_line] = STATE(27),
    [sym_superset_line] = STATE(27),
    [sym_superset_name] = STATE(26),
    [sym_exercise_line] = STATE(27),
    [sym_prose_line] = STATE(27),
    [sym_numeric_token] = STATE(4),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [aux_sym_superset_name_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LF] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(7),
    [sym_number_literal] = ACTIONS(3),
    [sym_word] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym_numeric_token] = STATE(21),
    [sym_token] = STATE(3),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [sym_note] = STATE(21),
    [aux_sym_continuation_line_repeat1] = STATE(3),
    [aux_sym_superset_name_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [sym_number_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(14),
  },
  [STATE(4)] = {
    [sym_numeric_token] = STATE(21),
    [sym_token] = STATE(5),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [sym_note] = STATE(21),
    [aux_sym_continuation_line_repeat1] = STATE(5),
    [aux_sym_superset_name_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(3),
    [sym_word] = ACTIONS(19),
  },
  [STATE(5)] = {
    [sym_numeric_token] = STATE(21),
    [sym_token] = STATE(3),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [sym_note] = STATE(21),
    [aux_sym_continuation_line_repeat1] = STATE(3),
    [aux_sym_superset_name_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(21),
    [sym_number_literal] = ACTIONS(3),
    [sym_word] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym_numeric_token] = STATE(21),
    [sym_token] = STATE(3),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [sym_note] = STATE(21),
    [aux_sym_continuation_line_repeat1] = STATE(3),
    [aux_sym_superset_name_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_number_literal] = ACTIONS(3),
    [sym_word] = ACTIONS(19),
  },
  [STATE(7)] = {
    [sym_numeric_token] = STATE(21),
    [sym_token] = STATE(3),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [sym_note] = STATE(21),
    [aux_sym_continuation_line_repeat1] = STATE(3),
    [aux_sym_superset_name_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(25),
    [sym_number_literal] = ACTIONS(3),
    [sym_word] = ACTIONS(19),
  },
  [STATE(8)] = {
    [sym_numeric_token] = STATE(21),
    [sym_token] = STATE(6),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [sym_note] = STATE(21),
    [aux_sym_continuation_line_repeat1] = STATE(6),
    [aux_sym_superset_name_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [sym_number_literal] = ACTIONS(3),
    [sym_word] = ACTIONS(19),
  },
  [STATE(9)] = {
    [sym_numeric_token] = STATE(8),
    [sym_by_expr] = STATE(16),
    [sym_two_part_by] = STATE(19),
    [sym_three_part_by] = STATE(19),
    [sym_multiplier] = STATE(16),
    [sym_partial_multiplier] = STATE(20),
    [sym_full_multiplier] = STATE(20),
    [sym_number] = STATE(16),
    [aux_sym_superset_name_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_DOT] = ACTIONS(29),
    [sym_number_literal] = ACTIONS(3),
    [sym_star] = ACTIONS(31),
    [sym_word] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_number_literal,
    ACTIONS(19), 1,
      sym_word,
    STATE(13), 1,
      aux_sym_superset_name_repeat1,
    STATE(7), 2,
      sym_token,
      aux_sym_continuation_line_repeat1,
    STATE(19), 2,
      sym_two_part_by,
      sym_three_part_by,
    STATE(20), 2,
      sym_partial_multiplier,
      sym_full_multiplier,
    STATE(21), 2,
      sym_numeric_token,
      sym_note,
    STATE(16), 3,
      sym_by_expr,
      sym_multiplier,
      sym_number,
  [31] = 4,
    ACTIONS(37), 1,
      sym_x_separator,
    ACTIONS(39), 1,
      sym_by_keyword,
    ACTIONS(41), 1,
      sym_word,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
  [47] = 3,
    ACTIONS(45), 1,
      sym_word,
    STATE(12), 1,
      aux_sym_superset_name_repeat1,
    ACTIONS(43), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
      sym_star,
  [61] = 3,
    ACTIONS(33), 1,
      sym_word,
    STATE(12), 1,
      aux_sym_superset_name_repeat1,
    ACTIONS(48), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
  [74] = 3,
    ACTIONS(52), 1,
      sym_by_keyword,
    ACTIONS(54), 1,
      sym_word,
    ACTIONS(50), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
  [87] = 3,
    ACTIONS(58), 1,
      sym_x_separator,
    ACTIONS(60), 1,
      sym_word,
    ACTIONS(56), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
  [100] = 1,
    ACTIONS(62), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
      sym_word,
  [108] = 4,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym__separator,
    STATE(18), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(66), 2,
      anon_sym_LF,
      anon_sym_DOT,
  [122] = 4,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym__separator,
    STATE(22), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(66), 2,
      anon_sym_LF,
      anon_sym_DOT,
  [136] = 1,
    ACTIONS(70), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
      sym_word,
  [144] = 1,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
      sym_word,
  [152] = 1,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
      sym_word,
  [160] = 4,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym__separator,
    STATE(22), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(78), 2,
      anon_sym_LF,
      anon_sym_DOT,
  [174] = 1,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
      sym_word,
  [182] = 1,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
      sym_number_literal,
      sym_word,
  [190] = 3,
    ACTIONS(31), 1,
      sym_star,
    ACTIONS(33), 1,
      sym_word,
    STATE(12), 1,
      aux_sym_superset_name_repeat1,
  [200] = 3,
    ACTIONS(85), 1,
      sym_word,
    STATE(10), 1,
      sym_superset_name,
    STATE(25), 1,
      aux_sym_superset_name_repeat1,
  [210] = 1,
    ACTIONS(76), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DOT,
  [216] = 1,
    ACTIONS(87), 2,
      sym_number_literal,
      sym_word,
  [221] = 1,
    ACTIONS(89), 1,
      sym_number_literal,
  [225] = 1,
    ACTIONS(91), 1,
      sym_number_literal,
  [229] = 1,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [233] = 1,
    ACTIONS(95), 1,
      sym_number_literal,
  [237] = 1,
    ACTIONS(97), 1,
      sym_number_literal,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 31,
  [SMALL_STATE(12)] = 47,
  [SMALL_STATE(13)] = 61,
  [SMALL_STATE(14)] = 74,
  [SMALL_STATE(15)] = 87,
  [SMALL_STATE(16)] = 100,
  [SMALL_STATE(17)] = 108,
  [SMALL_STATE(18)] = 122,
  [SMALL_STATE(19)] = 136,
  [SMALL_STATE(20)] = 144,
  [SMALL_STATE(21)] = 152,
  [SMALL_STATE(22)] = 160,
  [SMALL_STATE(23)] = 174,
  [SMALL_STATE(24)] = 182,
  [SMALL_STATE(25)] = 190,
  [SMALL_STATE(26)] = 200,
  [SMALL_STATE(27)] = 210,
  [SMALL_STATE(28)] = 216,
  [SMALL_STATE(29)] = 221,
  [SMALL_STATE(30)] = 225,
  [SMALL_STATE(31)] = 229,
  [SMALL_STATE(32)] = 233,
  [SMALL_STATE(33)] = 237,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_continuation_line_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_continuation_line_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_continuation_line_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation_line, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation_line, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_line, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_superset_line, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exercise_line, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose_line, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_superset_name_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_superset_name_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_two_part_by, 3, 0, 2),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_two_part_by, 3, 0, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial_multiplier, 3, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_partial_multiplier, 3, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numeric_token, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_by_expr, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplier, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_multiplier, 5, 0, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_three_part_by, 5, 0, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_superset_name, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [93] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_workout(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
